const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const CLEAR_TASKS = 'CLEAR_TASKS';
const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
const TOGGLE_SHOW = 'TOGGLE_SHOW';
const TOGGLE_THEME = 'TOGGLE_THEME';

export {
  ADD_TASK,
  REMOVE_TASK,
  CLEAR_TASKS,
  TOGGLE_COMPLETED,
  TOGGLE_SHOW,
  TOGGLE_THEME,
};
