const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const CLEAR_TASKS = 'CLEAR_TASKS';
const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_ACTIVE = 'SHOW_ACTIVE';
const SHOW_COMPLETED = 'SHOW_COMPLETED';
const TOGGLE_THEME = 'TOGGLE_THEME';

export {
  ADD_TASK,
  REMOVE_TASK,
  CLEAR_TASKS,
  TOGGLE_COMPLETED,
  SHOW_ALL,
  SHOW_ACTIVE,
  SHOW_COMPLETED,
  TOGGLE_THEME,
};
